USE algoritmos;


  

--
-- Contenu de la table `CodigosPostales`
--

INSERT INTO  distrito_federal VALUES
(1,1000, 'San Angel', 'Álvaro Obregón', 'Distrito Federal'),
(2,1010, 'Los Alpes', 'Álvaro Obregón', 'Distrito Federal'),
(3,1020, 'Guadalupe Inn', 'Álvaro Obregón', 'Distrito Federal'),
(4,1028, 'Secretaria de Contraloría y Desarrollo Administrativo', 'Álvaro Obregón', 'Distrito Federal'),
(5,1029, 'INFONAVIT', 'Álvaro Obregón', 'Distrito Federal'),
(6,1030, 'Florida;Axotla', 'Álvaro Obregón', 'Distrito Federal'),
(7,1040, 'Campestre', 'Álvaro Obregón', 'Distrito Federal'),
(8,1048, 'Las Águilas', 'Álvaro Obregón', 'Distrito Federal'),
(9,1049, 'Tlacopac', 'Álvaro Obregón', 'Distrito Federal'),
(10,1050, 'Ex-Hacienda de Guadalupe Chimalistac', 'Álvaro Obregón', 'Distrito Federal'),
(11,1060, 'Altavista;San Angel Inn', 'Álvaro Obregón', 'Distrito Federal'),
(12,1070, 'Chimalistac', 'Álvaro Obregón', 'Distrito Federal'),
(13,1080, 'Progreso Tizapan', 'Álvaro Obregón', 'Distrito Federal'),
(14,1089, 'Ermita Tizapan', 'Álvaro Obregón', 'Distrito Federal'),
(15,1090, 'Tizapan;Loreto;La Otra Banda', 'Álvaro Obregón', 'Distrito Federal'),
(16,1100, 'Pólvora;Lomas de Santo Domingo', 'Álvaro Obregón', 'Distrito Federal'),
(17,1109, 'La Conchita', 'Álvaro Obregón', 'Distrito Federal'),
(18,1110, 'Ampliación El Capulin;El Capulín;Liberales de 1857;Belém de las Flores', 'Álvaro Obregón', 'Distrito Federal'),
(19,1116, 'Secretaria de la Policia Federal Preventiva', 'Álvaro Obregón', 'Distrito Federal'),
(20,1120, 'Las Américas;Sears Roebuck;Acueducto;Hidalgo;Cove', 'Álvaro Obregón', 'Distrito Federal'),
(21,1125, 'Ampliación Acueducto', 'Álvaro Obregón', 'Distrito Federal'),
(22,1130, 'Paraíso;Real del Monte;Molino de Santo Domingo;Molino de Santo Domingo', 'Álvaro Obregón', 'Distrito Federal'),
(23,1139, 'Reacomodo Pino Suárez', 'Álvaro Obregón', 'Distrito Federal'),
(24,1140, 'Bellavista;José Maria Pino Suárez', 'Álvaro Obregón', 'Distrito Federal'),
(25,1150, 'Tolteca;Cristo Rey', 'Álvaro Obregón', 'Distrito Federal'),
(26,1159, 'Delegación Política Álvaro Obregón', 'Álvaro Obregón', 'Distrito Federal'),
(27,1160, 'Bosque;Maria G. de García Ruiz;1a Victoria;Isidro Fabela', 'Álvaro Obregón', 'Distrito Federal'),
(28,1170, 'Santa Fe IMSS;Abraham M. González', 'Álvaro Obregón', 'Distrito Federal'),
(29,1180, '8 de Agosto;Carola;San Pedro de los Pinos', 'Álvaro Obregón', 'Distrito Federal'),
(30,1184, 'Nelli Campo Bello', 'Álvaro Obregón', 'Distrito Federal'),
(31,1200, 'Arturo Martínez', 'Álvaro Obregón', 'Distrito Federal'),
(32,1209, 'Belén', 'Álvaro Obregón', 'Distrito Federal'),
(33,1210, 'Santa Fe', 'Álvaro Obregón', 'Distrito Federal'),
(34,1219, 'Lomas de Santa Fe', 'Álvaro Obregón', 'Distrito Federal'),
(35,1220, 'Bonanza;Cuevitas;La Estrella;Mártires de Tacubaya;El Cuernito;Zenón Delgado', 'Álvaro Obregón', 'Distrito Federal'),
(36,1230, 'Tlapechico;El Piru Santa Fe;El Piru 2a Ampliación;Los Gamitos;Campo de Tiro los Gamitos', 'Álvaro Obregón', 'Distrito Federal'),
(37,1239, 'La Huerta', 'Álvaro Obregón', 'Distrito Federal'),
(38,1240, 'Pueblo Nuevo', 'Álvaro Obregón', 'Distrito Federal'),
(39,1250, 'Margarita Maza de Juárez;El Árbol;Ladera;Tecolalco;Lomas de Nuevo México', 'Álvaro Obregón', 'Distrito Federal'),
(40,1259, 'Ampliación La Cebada;La Mexicana 2a Ampliación', 'Álvaro Obregón', 'Distrito Federal'),
(41,1260, 'La Mexicana;La Palmita;Liberación Proletaria;Calzada Jalalpa;Ampliación La Mexicana', 'Álvaro Obregón', 'Distrito Federal'),
(42,1269, '1a Sección Cañada;2a Sección Cañada', 'Álvaro Obregón', 'Distrito Federal'),
(43,1270, 'Golondrinas 2a Sección;La Presa;El Tejocote;Lomas de Capula;Golondrinas;Golondrinas 1a Sección', 'Álvaro Obregón', 'Distrito Federal'),
(44,1275, 'Villa Solidaridad', 'Álvaro Obregón', 'Distrito Federal'),
(45,1276, 'El Pirul', 'Álvaro Obregón', 'Distrito Federal'),
(46,1278, 'Desarrollo Urbano', 'Álvaro Obregón', 'Distrito Federal'),
(47,1279, 'Lomas de Becerra', 'Álvaro Obregón', 'Distrito Federal'),
(48,1280, 'Francisco Villa;Lomas de Becerra;El Pocito;Arvide;La Joya', 'Álvaro Obregón', 'Distrito Federal'),
(49,1285, 'El Rodeo', 'Álvaro Obregón', 'Distrito Federal'),
(50,1289, 'Reacomodo El Cuernito', 'Álvaro Obregón', 'Distrito Federal'),
(51,1290, 'Piloto Adolfo López Mateos;Presidentes', 'Álvaro Obregón', 'Distrito Federal'),
(52,1296, 'Jalalpa Tepito 2a Ampliación;Ampliación Jalalpa;Jalalpa Tepito', 'Álvaro Obregón', 'Distrito Federal'),
(53,1298, 'Ampliación Piloto Adolfo López Mateos', 'Álvaro Obregón', 'Distrito Federal'),
(54,1299, '1a Ampliación Presidentes;2a Ampliación Presidentes', 'Álvaro Obregón', 'Distrito Federal'),
(55,1310, 'San Gabriel', 'Álvaro Obregón', 'Distrito Federal'),
(56,1320, 'Carlos A. Madrazo', 'Álvaro Obregón', 'Distrito Federal'),
(57,1330, 'Paseo de las Lomas', 'Álvaro Obregón', 'Distrito Federal'),
(58,1340, 'Bejero del Pueblo Santa Fe', 'Álvaro Obregón', 'Distrito Federal'),
(59,1376, 'Santa Fe Peña Blanca;Santa Fe;Santa Fe La Loma;Santa Fe Centro Ciudad', 'Álvaro Obregón', 'Distrito Federal'),
(60,1377, 'Jalalpa El Grande', 'Álvaro Obregón', 'Distrito Federal'),
(61,1379, 'Antonio Carrillo Flores', 'Álvaro Obregón', 'Distrito Federal'),
(62,1389, 'Santa Fe Tlayapaca', 'Álvaro Obregón', 'Distrito Federal'),
(63,1400, 'Olivar del Conde 1a Sección;Preconcreto', 'Álvaro Obregón', 'Distrito Federal'),
(64,1407, 'Galeana', 'Álvaro Obregón', 'Distrito Federal'),
(65,1408, 'Olivar del Conde 2a Sección', 'Álvaro Obregón', 'Distrito Federal'),
(66,1410, 'Palmas;Barrio Norte', 'Álvaro Obregón', 'Distrito Federal'),
(67,1419, 'Minas Cristo Rey', 'Álvaro Obregón', 'Distrito Federal'),
(68,1420, 'Santa María Nonoalco;Sacramento', 'Álvaro Obregón', 'Distrito Federal'),
(69,1430, 'Colina del Sur', 'Álvaro Obregón', 'Distrito Federal'),
(70,1440, 'Abeto', 'Álvaro Obregón', 'Distrito Federal'),
(71,1450, 'Unidad Popular Emiliano Zapata;Cañada del Olivar;Batallón de San Patricio;Hogar y Redención', 'Álvaro Obregón', 'Distrito Federal'),
(72,1460, 'Alfonso XIII', 'Álvaro Obregón', 'Distrito Federal'),
(73,1470, 'Molino de Rosas;Alfalfar', 'Álvaro Obregón', 'Distrito Federal'),
(74,1480, 'Lomas de Plateros', 'Álvaro Obregón', 'Distrito Federal'),
(75,1490, 'La Cascada;Torres de Mixcoac', 'Álvaro Obregón', 'Distrito Federal'),
(76,1500, 'Santa Lucia;Miguel Gaona Armenta', 'Álvaro Obregón', 'Distrito Federal'),
(77,1504, '19 de Mayo', 'Álvaro Obregón', 'Distrito Federal'),
(78,1505, 'Milpa los Cedros', 'Álvaro Obregón', 'Distrito Federal'),
(79,1506, 'Arturo Gamiz', 'Álvaro Obregón', 'Distrito Federal'),
(80,1507, 'Tetlalpan', 'Álvaro Obregón', 'Distrito Federal'),
(81,1508, 'Ladera Chica', 'Álvaro Obregón', 'Distrito Federal'),
(82,1509, 'Santa Lucía Chantepec', 'Álvaro Obregón', 'Distrito Federal'),
(83,1510, 'La Araña;Garcimarrero;Los Cedros', 'Álvaro Obregón', 'Distrito Federal'),
(84,1520, 'Estado de Hidalgo;Ampliación Estado de Hidalgo;Ampliación Los Pirules;Piru Santa Lucia;El Politoco', 'Álvaro Obregón', 'Distrito Federal'),
(85,1530, 'Corpus Christy', 'Álvaro Obregón', 'Distrito Federal'),
(86,1537, 'Universal', 'Álvaro Obregón', 'Distrito Federal'),
(87,1538, 'Tepopotla', 'Álvaro Obregón', 'Distrito Federal'),
(88,1539, 'Cooperativa Unión Olivos;Acuilotla', 'Álvaro Obregón', 'Distrito Federal'),
(89,1540, 'Cehuaya;Balcones de Cehuayo;Providencia;Punta de Cehuaya;Llano Redondo', 'Álvaro Obregón', 'Distrito Federal'),
(90,1548, 'Villa Progresista', 'Álvaro Obregón', 'Distrito Federal'),
(91,1549, 'Dos Ríos del Pueblo Santa Lucía', 'Álvaro Obregón', 'Distrito Federal'),
(92,1550, 'Tepeaca;Ampliación Tepeaca;Rinconada Las Cuevitas', 'Álvaro Obregón', 'Distrito Federal'),
(93,1560, 'Canutillo;Ave Real;Canutillo 2a Sección;Canutillo 3a Sección', 'Álvaro Obregón', 'Distrito Federal'),
(94,1566, 'Hueytlale', 'Álvaro Obregón', 'Distrito Federal'),
(95,1567, 'Tepeaca', 'Álvaro Obregón', 'Distrito Federal'),
(96,1569, 'Reacomodo Valentín Gómez Farías', 'Álvaro Obregón', 'Distrito Federal'),
(97,1580, 'Bosques de Tarango;Rancho Casa Blanca', 'Álvaro Obregón', 'Distrito Federal'),
(98,1585, 'Las Haciendas', 'Álvaro Obregón', 'Distrito Federal'),
(99,1586, 'Real de Tarango', 'Álvaro Obregón', 'Distrito Federal'),
(100,1587, 'Misiones de Tarango', 'Álvaro Obregón', 'Distrito Federal'),
(101,1588, 'Tarango', 'Álvaro Obregón', 'Distrito Federal'),
(102,1589, 'Lomas de Tarango Reacomodo', 'Álvaro Obregón', 'Distrito Federal'),
(103,1590, 'El Rincón', 'Álvaro Obregón', 'Distrito Federal'),
(104,1600, 'Merced Gómez;Sociedad Cooperativa Unión Poder Popular', 'Álvaro Obregón', 'Distrito Federal'),
(105,1610, 'Profesor J. Arturo López Martínez;Colinas de Tarango', 'Álvaro Obregón', 'Distrito Federal'),
(106,1618, 'Ex-Hacienda de Tarango;Arcos Centenario', 'Álvaro Obregón', 'Distrito Federal'),
(107,1619, 'La Martinica;Rinconada de Tarango', 'Álvaro Obregón', 'Distrito Federal'),
(108,1620, 'Lomas de Tarango', 'Álvaro Obregón', 'Distrito Federal'),
(109,1630, 'Puerta Grande;Belém de las Flores;Los Juristas;Lomas de Puerta Grande', 'Álvaro Obregón', 'Distrito Federal'),
(110,1640, 'Heron Proal', 'Álvaro Obregón', 'Distrito Federal'),
(111,1645, 'Ponciano Arriaga', 'Álvaro Obregón', 'Distrito Federal'),
(112,1650, 'Tlacuitlapa;Ampliación Tlacuitlapa;2o Reacomodo Tlacuitlapa;Palmas Axotitla;El Ruedo;Santa Lucía Chantepec;La Milagrosa', 'Álvaro Obregón', 'Distrito Federal'),
(113,1700, 'Tecalcapa del Pueblo Tetelpan;Tetelpan;San Agustín del Pueblo Tetelpan;2a Del Moral del Pueblo de Tetelpan;La Joyita del Pueblo Tetelpan;Ocotillos del Pueblo Tetelpan', 'Álvaro Obregón', 'Distrito Federal'),
(114,1708, 'El Mirador del Pueblo Tetelpan;El Encino del Pueblo Tetelpan', 'Álvaro Obregón', 'Distrito Federal'),
(115,1710, 'Ampliación Alpes;Las Águilas', 'Álvaro Obregón', 'Distrito Federal'),
(116,1720, 'Lomas de Guadalupe', 'Álvaro Obregón', 'Distrito Federal'),
(117,1729, 'Alcantarilla', 'Álvaro Obregón', 'Distrito Federal'),
(118,1730, 'Lomas de las Águilas;Puente Colorado', 'Álvaro Obregón', 'Distrito Federal'),
(119,1740, 'La Peñita del Pueblo Tetelpan;San Clemente Norte;San Clemente Sur', 'Álvaro Obregón', 'Distrito Federal'),
(120,1750, 'Las Aguilas 3er Parque;Las Aguilas 2o Parque;Las Aguilas 1a Sección', 'Álvaro Obregón', 'Distrito Federal'),
(121,1759, 'Ampliación Las Aguilas', 'Álvaro Obregón', 'Distrito Federal'),
(122,1760, 'Flor de Maria;Atlamaya;La Herradura del Pueblo Tetelpan', 'Álvaro Obregón', 'Distrito Federal'),
(123,1770, 'La Angostura;San José del Olivar', 'Álvaro Obregón', 'Distrito Federal'),
(124,1780, 'Olivar de los Padres;Tizampampano del Pueblo Tetelpan', 'Álvaro Obregón', 'Distrito Federal'),
(125,1788, 'El Olivarito', 'Álvaro Obregón', 'Distrito Federal'),
(126,1789, 'Miguel Hidalgo', 'Álvaro Obregón', 'Distrito Federal'),
(128,1790, 'Lomas de San Ángel Inn;Lomas de los Angeles del Pueblo Tetelpan', 'Álvaro Obregón', 'Distrito Federal'),
(129,1800, 'San Bartolo Ameyalco', 'Álvaro Obregón', 'Distrito Federal'),
(130,1807, 'Rancho San Francisco Pueblo San Bartolo Ameyalco', 'Álvaro Obregón', 'Distrito Federal'),
(131,1810, 'Villa Verdún', 'Álvaro Obregón', 'Distrito Federal'),
(132,1820, 'Lomas Axomiatla', 'Álvaro Obregón', 'Distrito Federal'),
(133,1830, 'Santa Rosa Xochiac', 'Álvaro Obregón', 'Distrito Federal'),
(134,1840, 'Torres de Potrero', 'Álvaro Obregón', 'Distrito Federal'),
(135,1849, 'Rancho del Carmen del Pueblo San Bartolo Ameyalco;Rincón de La Bolsa', 'Álvaro Obregón', 'Distrito Federal'),
(136,1856, 'Paraje del Caballito', 'Álvaro Obregón', 'Distrito Federal'),
(137,1857, 'Lomas de Chamontoya', 'Álvaro Obregón', 'Distrito Federal'),
(138,1859, 'Tlacoyaque', 'Álvaro Obregón', 'Distrito Federal'),
(139,1860, 'Lomas de La Era', 'Álvaro Obregón', 'Distrito Federal'),
(140,1870, 'Lomas de los Cedros', 'Álvaro Obregón', 'Distrito Federal'),
(141,1900, 'Jardines del Pedregal', 'Álvaro Obregón', 'Distrito Federal'),
(142,1904, 'San Jerónimo Aculco', 'Álvaro Obregón', 'Distrito Federal'),
(143,1940, 'Rancho Anzaldo y Contreras', 'Álvaro Obregón', 'Distrito Federal'),
(144,1990, 'Pedregal', 'Álvaro Obregón', 'Distrito Federal'),
(145,2000, 'Centro de Azcapotzalco', 'Azcapotzalco', 'Distrito Federal'),
(146,2008, 'Delegación Política Azcapotzalco', 'Azcapotzalco', 'Distrito Federal'),
(148,2010, 'San Rafael;Los Reyes;Nuevo Barrio San Rafael', 'Azcapotzalco', 'Distrito Federal'),
(149,2020, 'Santo Tomas;San Marcos', 'Azcapotzalco', 'Distrito Federal'),
(150,2040, 'San Sebastián;Del Maestro', 'Azcapotzalco', 'Distrito Federal'),
(151,2050, 'Wake;Santa Maria Malinalco;Libertad', 'Azcapotzalco', 'Distrito Federal'),
(152,2060, 'Sindicato Mexicano de Electricistas;Un Hogar Para Cada Trabajador', 'Azcapotzalco', 'Distrito Federal'),
(153,2070, 'Nextengo;Del Recreo;Palestina;Nextengo;Azcapotzalco', 'Azcapotzalco', 'Distrito Federal'),
(154,2080, 'Sector Naval;Clavería', 'Azcapotzalco', 'Distrito Federal'),
(155,2090, 'San Álvaro', 'Azcapotzalco', 'Distrito Federal'),
(156,2099, 'Angel Zimbron', 'Azcapotzalco', 'Distrito Federal'),
(157,2100, 'El Rosario;Los Oyameles', 'Azcapotzalco', 'Distrito Federal'),
(158,2109, 'CROC 6 Olimpia;Manuel Rivera Anaya CROC 1', 'Azcapotzalco', 'Distrito Federal'),
(159,2110, 'Ecológica Novedades Impacto;San Pablo Xalpa', 'Azcapotzalco', 'Distrito Federal'),
(160,2120, 'San Martín Xochinahuac', 'Azcapotzalco', 'Distrito Federal'),
(161,2125, 'San Martín Xochinahuac', 'Azcapotzalco', 'Distrito Federal'),
(162,2127, 'Tepantongo', 'Azcapotzalco', 'Distrito Federal'),
(163,2128, 'Nueva El Rosario', 'Azcapotzalco', 'Distrito Federal'),
(164,2129, 'Nueva España', 'Azcapotzalco', 'Distrito Federal'),
(165,2130, 'Tierra Nueva', 'Azcapotzalco', 'Distrito Federal'),
(166,2140, 'Santa Ines', 'Azcapotzalco', 'Distrito Federal'),
(167,2150, 'Pasteros;Azcapotzalco Pasteros', 'Azcapotzalco', 'Distrito Federal'),
(168,2160, 'Santo Domingo', 'Azcapotzalco', 'Distrito Federal'),
(169,2169, 'Villas de Azcapotzalco', 'Azcapotzalco', 'Distrito Federal'),
(170,2200, 'Reynosa Tamaulipas', 'Azcapotzalco', 'Distrito Federal'),
(171,2230, 'Santa Bárbara', 'Azcapotzalco', 'Distrito Federal'),
(172,2240, 'Ticoman;San Andrés;San Andrés Fase II;San Andrés', 'Azcapotzalco', 'Distrito Federal'),
(173,2250, 'Santa Catarina', 'Azcapotzalco', 'Distrito Federal'),
(174,2260, 'Pitolaca', 'Azcapotzalco', 'Distrito Federal'),
(175,2300, 'Industrial Vallejo', 'Azcapotzalco', 'Distrito Federal'),
(176,2310, 'Ferrería', 'Azcapotzalco', 'Distrito Federal'),
(177,2320, 'San Andrés de las Salinas', 'Azcapotzalco', 'Distrito Federal'),
(178,2330, 'Huautla de las Salinas', 'Azcapotzalco', 'Distrito Federal'),
(179,2340, 'Santa Cruz de las Salinas', 'Azcapotzalco', 'Distrito Federal'),
(180,2350, 'Jardines de Ceylán', 'Azcapotzalco', 'Distrito Federal'),
(181,2360, 'Las Salinas', 'Azcapotzalco', 'Distrito Federal'),
(182,2400, 'Rinconada el Olivar;San Juan Tlihuaca;San Juan Tlihuaca', 'Azcapotzalco', 'Distrito Federal'),
(183,2409, 'Rosendo Salazar', 'Azcapotzalco', 'Distrito Federal'),
(184,2410, 'Prados del Rosario', 'Azcapotzalco', 'Distrito Federal'),
(185,2419, 'Trabajadores de PEMEX', 'Azcapotzalco', 'Distrito Federal'),
(186,2420, 'Francisco Villa;Ex-Hacienda El Rosario', 'Azcapotzalco', 'Distrito Federal'),
(187,2430, 'Presidente Madero', 'Azcapotzalco', 'Distrito Federal'),
(188,2440, 'Providencia', 'Azcapotzalco', 'Distrito Federal'),
(190,2450, 'Miguel Hidalgo;Las Trancas', 'Azcapotzalco', 'Distrito Federal'),
(191,2459, 'Tezozomoc', 'Azcapotzalco', 'Distrito Federal'),
(192,2460, 'Axolahua;La Preciosa', 'Azcapotzalco', 'Distrito Federal'),
(193,2470, 'Ampliación Petrolera', 'Azcapotzalco', 'Distrito Federal'),
(194,2479, 'Lázaro Cárdenas', 'Azcapotzalco', 'Distrito Federal'),
(195,2480, 'Petrolera', 'Azcapotzalco', 'Distrito Federal'),
(196,2490, 'Kervin;San Mateo', 'Azcapotzalco', 'Distrito Federal'),
(197,2500, 'Unidad Cuitlahuac', 'Azcapotzalco', 'Distrito Federal'),
(198,2510, 'El Jagüey;Pantaco', 'Azcapotzalco', 'Distrito Federal'),
(199,2519, 'El Jagüey', 'Azcapotzalco', 'Distrito Federal'),
(200,2520, 'Estación Pantaco', 'Azcapotzalco', 'Distrito Federal'),
(201,2525, 'Granjas Pantaco Campamento Ferrocarrilero', 'Azcapotzalco', 'Distrito Federal'),
(202,2530, 'Jardín Azpeitia', 'Azcapotzalco', 'Distrito Federal'),
(203,2540, 'Hogares Ferrocarrileros', 'Azcapotzalco', 'Distrito Federal'),
(204,2600, 'Pro-Hogar', 'Azcapotzalco', 'Distrito Federal'),
(205,2630, 'Coltongo;Coltongo', 'Azcapotzalco', 'Distrito Federal'),
(206,2640, 'Monte Alto', 'Azcapotzalco', 'Distrito Federal'),
(207,2650, 'Trabajadores de Hierro', 'Azcapotzalco', 'Distrito Federal'),
(208,2660, 'Euzkadi', 'Azcapotzalco', 'Distrito Federal'),
(209,2670, 'Cosmopolita', 'Azcapotzalco', 'Distrito Federal'),
(210,2680, 'Potrero del Llano', 'Azcapotzalco', 'Distrito Federal'),
(211,2700, 'San Miguel Amantla', 'Azcapotzalco', 'Distrito Federal'),
(212,2710, 'San Isidro;San Pedro Xalpa', 'Azcapotzalco', 'Distrito Federal'),
(213,2718, 'Las Armas', 'Azcapotzalco', 'Distrito Federal'),
(214,2719, 'Ampliación San Pedro Xalpa', 'Azcapotzalco', 'Distrito Federal'),
(215,2720, 'San Antonio;San Bartolo Cahualtongo', 'Azcapotzalco', 'Distrito Federal'),
(216,2729, 'Campo Encantado', 'Azcapotzalco', 'Distrito Federal'),
(217,2730, 'San Francisco Tetecala', 'Azcapotzalco', 'Distrito Federal'),
(218,2739, 'Miguel Lerdo de Tejada', 'Azcapotzalco', 'Distrito Federal'),
(219,2750, 'La Providencia;Santiago Ahuizotla;La Escuadra', 'Azcapotzalco', 'Distrito Federal'),
(220,2760, 'Santa Lucia;Industrial San Antonio', 'Azcapotzalco', 'Distrito Federal'),
(221,2770, 'Santa Cruz Acayucan', 'Azcapotzalco', 'Distrito Federal'),
(222,2780, 'Plenitud', 'Azcapotzalco', 'Distrito Federal'),
(223,2790, 'Santa Apolonia', 'Azcapotzalco', 'Distrito Federal'),
(224,2800, 'Nueva Santa Maria', 'Azcapotzalco', 'Distrito Federal'),
(225,2810, 'Ignacio Allende;Victoria de las Democracias', 'Azcapotzalco', 'Distrito Federal'),
(226,2830, 'San Bernabé;Toronja', 'Azcapotzalco', 'Distrito Federal'),
(227,2840, 'Obrero Popular;Cobre de México', 'Azcapotzalco', 'Distrito Federal'),
(228,2850, 'Tlatilco', 'Azcapotzalco', 'Distrito Federal'),
(229,2860, 'Tlatilco', 'Azcapotzalco', 'Distrito Federal'),
(230,2870, 'San Salvador Xochimanca', 'Azcapotzalco', 'Distrito Federal'),
(231,2900, 'Aguilera', 'Azcapotzalco', 'Distrito Federal'),
(232,2910, 'Aldana', 'Azcapotzalco', 'Distrito Federal'),
(234,2920, 'Ampliación Cosmopolita', 'Azcapotzalco', 'Distrito Federal'),
(235,2930, 'Liberación', 'Azcapotzalco', 'Distrito Federal'),
(236,2940, 'Porvenir', 'Azcapotzalco', 'Distrito Federal'),
(237,2950, 'Del Gas', 'Azcapotzalco', 'Distrito Federal'),
(238,2960, 'San Francisco Xocotitla', 'Azcapotzalco', 'Distrito Federal'),
(239,2970, 'Ampliación Del Gas', 'Azcapotzalco', 'Distrito Federal'),
(240,2980, 'Arenal;Patrimonio Familiar', 'Azcapotzalco', 'Distrito Federal'),
(241,2990, 'La Raza', 'Azcapotzalco', 'Distrito Federal'),
(242,3000, 'Piedad Narvarte', 'Benito Juárez', 'Distrito Federal'),
(243,3010, 'Atenor Salas', 'Benito Juárez', 'Distrito Federal'),
(244,3020, 'Esperanza;Narvarte Poniente', 'Benito Juárez', 'Distrito Federal'),
(245,3023, 'Unidad Narvarte IMSS;Narvarte Oriente', 'Benito Juárez', 'Distrito Federal'),
(246,3027, 'Unidad de Pagos de La SCT', 'Benito Juárez', 'Distrito Federal'),
(247,3028, 'Secretaria de Comunicaciones y Transportes', 'Benito Juárez', 'Distrito Federal'),
(248,3100, 'Del Valle Centro;Insurgentes San Borja', 'Benito Juárez', 'Distrito Federal'),
(249,3103, 'Del Valle Norte', 'Benito Juárez', 'Distrito Federal'),
(250,3104, 'Del Valle Sur', 'Benito Juárez', 'Distrito Federal'),
(251,3109, 'Partido Acción Nacional', 'Benito Juárez', 'Distrito Federal'),
(252,3199, 'Cámara Nacional de la Industria del Hierro y Acero', 'Benito Juárez', 'Distrito Federal'),
(253,3200, 'Tlacoquemecatl', 'Benito Juárez', 'Distrito Federal'),
(254,3219, 'La Interamericana Compañía de Seguros S.A.', 'Benito Juárez', 'Distrito Federal'),
(255,3220, 'Centro Urbano Presidente Miguel Alemán', 'Benito Juárez', 'Distrito Federal'),
(256,3229, 'Centro Hospitalario 20 de Noviembre', 'Benito Juárez', 'Distrito Federal'),
(257,3230, 'Actipan', 'Benito Juárez', 'Distrito Federal'),
(258,3240, 'Acacias', 'Benito Juárez', 'Distrito Federal'),
(259,3300, 'Portales Sur', 'Benito Juárez', 'Distrito Federal'),
(260,3303, 'Portales Norte', 'Benito Juárez', 'Distrito Federal'),
(261,3310, 'Santa Cruz Atoyac', 'Benito Juárez', 'Distrito Federal'),
(262,3313, 'Modulo Social las Flores', 'Benito Juárez', 'Distrito Federal'),
(263,3319, 'Delegación Política Benito Juárez', 'Benito Juárez', 'Distrito Federal'),
(264,3320, 'Residencial Emperadores', 'Benito Juárez', 'Distrito Federal'),
(265,3330, 'Xoco', 'Benito Juárez', 'Distrito Federal'),
(266,3339, 'Bancomer S.A.', 'Benito Juárez', 'Distrito Federal'),
(267,3340, 'General Pedro Maria Anaya', 'Benito Juárez', 'Distrito Federal'),
(268,3400, 'Álamos', 'Benito Juárez', 'Distrito Federal'),
(269,3410, 'Postal', 'Benito Juárez', 'Distrito Federal'),
(270,3420, 'Miguel Alemán', 'Benito Juárez', 'Distrito Federal'),
(271,3430, 'Josefa Ortiz de Domínguez', 'Benito Juárez', 'Distrito Federal'),
(273,3440, 'Niños Héroes', 'Benito Juárez', 'Distrito Federal'),
(274,3500, 'Nativitas', 'Benito Juárez', 'Distrito Federal'),
(275,3510, 'Moderna', 'Benito Juárez', 'Distrito Federal'),
(276,3520, 'Iztaccihuatl', 'Benito Juárez', 'Distrito Federal'),
(277,3530, 'Villa de Cortes', 'Benito Juárez', 'Distrito Federal'),
(278,3540, 'Del Carmen', 'Benito Juárez', 'Distrito Federal'),
(279,3550, 'Zacahuitzco', 'Benito Juárez', 'Distrito Federal'),
(280,3560, 'Albert', 'Benito Juárez', 'Distrito Federal'),
(281,3570, 'Portales Oriente', 'Benito Juárez', 'Distrito Federal'),
(282,3580, 'Miravalle', 'Benito Juárez', 'Distrito Federal'),
(283,3590, 'Ermita', 'Benito Juárez', 'Distrito Federal'),
(284,3600, 'Vertiz Narvarte', 'Benito Juárez', 'Distrito Federal'),
(285,3610, 'Américas Unidas', 'Benito Juárez', 'Distrito Federal'),
(286,3620, 'Periodista', 'Benito Juárez', 'Distrito Federal'),
(287,3630, 'Independencia', 'Benito Juárez', 'Distrito Federal'),
(289,3640, 'Del Lago', 'Benito Juárez', 'Distrito Federal'),
(290,3650, 'Letrán Valle', 'Benito Juárez', 'Distrito Federal'),
(291,3660, 'San Simón Ticumac', 'Benito Juárez', 'Distrito Federal'),
(292,3700, 'Santa Maria Nonoalco', 'Benito Juárez', 'Distrito Federal'),
(293,3710, 'Ciudad de los Deportes', 'Benito Juárez', 'Distrito Federal'),
(294,3720, 'Nochebuena', 'Benito Juárez', 'Distrito Federal'),
(295,3730, 'San Juan', 'Benito Juárez', 'Distrito Federal'),
(296,3740, 'Extremadura Insurgentes', 'Benito Juárez', 'Distrito Federal'),
(297,3800, 'San Pedro de los Pinos', 'Benito Juárez', 'Distrito Federal'),
(298,3809, 'Procuraduría Federal Fiscal', 'Benito Juárez', 'Distrito Federal'),
(299,3810, 'Napoles', 'Benito Juárez', 'Distrito Federal'),
(300,3818, 'The Sidney Ross Co S.A.', 'Benito Juárez', 'Distrito Federal'),
(301,3819, 'World Trade Center Ciudad de México', 'Benito Juárez', 'Distrito Federal'),
(302,3820, '8 de Agosto', 'Benito Juárez', 'Distrito Federal'),
(303,3840, 'Ampliación Napoles', 'Benito Juárez', 'Distrito Federal'),
(304,3849, 'Cámara Nacional de la Industria de Transformación', 'Benito Juárez', 'Distrito Federal'),
(305,3900, 'San José Insurgentes', 'Benito Juárez', 'Distrito Federal'),
(306,3910, 'Mixcoac', 'Benito Juárez', 'Distrito Federal'),
(307,3920, 'Insurgentes Mixcoac', 'Benito Juárez', 'Distrito Federal'),
(308,3930, 'Merced Gómez', 'Benito Juárez', 'Distrito Federal'),
(309,3940, 'Crédito Constructor', 'Benito Juárez', 'Distrito Federal'),
(310,3949, 'Consejo Nacional de La Ciencia y Tecnología', 'Benito Juárez', 'Distrito Federal'),
(311,4000, 'Villa Coyoacán', 'Coyoacán', 'Distrito Federal'),
(312,4009, 'Delegación Política Coyoacán', 'Coyoacán', 'Distrito Federal'),
(313,4010, 'Barrio Santa Catarina', 'Coyoacán', 'Distrito Federal'),
(314,4020, 'Barrio La Concepción', 'Coyoacán', 'Distrito Federal'),
(315,4030, 'Barrio San Lucas', 'Coyoacán', 'Distrito Federal'),
(316,4040, 'Parque San Andrés', 'Coyoacán', 'Distrito Federal'),
(317,4100, 'Del Carmen', 'Coyoacán', 'Distrito Federal'),
(318,4110, 'Viveros de Coyoacán', 'Coyoacán', 'Distrito Federal'),
(319,4120, 'San Mateo;San Diego Churubusco', 'Coyoacán', 'Distrito Federal'),
(320,4129, 'Cámara Nacional de la Industria Editorial', 'Coyoacán', 'Distrito Federal'),
(321,4200, 'Campestre Churubusco', 'Coyoacán', 'Distrito Federal'),
(322,4210, 'Churubusco Country Club', 'Coyoacán', 'Distrito Federal'),
(323,4230, 'Prado Churubusco', 'Coyoacán', 'Distrito Federal'),
(324,4239, 'Ermita Churubusco', 'Coyoacán', 'Distrito Federal'),
(325,4240, 'Hermosillo', 'Coyoacán', 'Distrito Federal'),
(326,4250, 'Paseos de Taxqueña', 'Coyoacán', 'Distrito Federal'),
(327,4259, '20 de Agosto', 'Coyoacán', 'Distrito Federal'),
(328,4260, 'San Francisco Culhuacán Barrio de San Juan;San Francisco Culhuacán Barrio de San Francisco;San Francisco Culhuacán Barrio de La Magdalena;San Francisco Culhuacán Barrio de Santa Ana', 'Coyoacán', 'Distrito Federal'),
(329,4270, 'Santa Martha del Sur Quetzalcoatl', 'Coyoacán', 'Distrito Federal'),
(330,4280, 'Taxqueña', 'Coyoacán', 'Distrito Federal'),
(331,4300, 'Ajusco', 'Coyoacán', 'Distrito Federal'),
(332,4307, 'Ajusco Montserrat', 'Coyoacán', 'Distrito Federal'),
(333,4309, 'Pedregal de Monserrat', 'Coyoacán', 'Distrito Federal'),
(334,4310, 'Romero de Terreros;Monte de Piedad', 'Coyoacán', 'Distrito Federal'),
(335,4317, 'ISSSTE', 'Coyoacán', 'Distrito Federal'),
(336,4318, 'Barrio Oxtopulco Universidad', 'Coyoacán', 'Distrito Federal'),
(337,4319, 'Torres de Chimalistac;Fortín de Chimalistac', 'Coyoacán', 'Distrito Federal'),
(338,4320, 'Romero de Terreros;Cuadrante de San Francisco;Pedregal de San Francisco', 'Coyoacán', 'Distrito Federal'),
(339,4326, 'Villa de San Francisco', 'Coyoacán', 'Distrito Federal'),
(340,4327, 'Rincón de Guanajuato', 'Coyoacán', 'Distrito Federal'),
(341,4330, 'Rinconada de los Reyes;Pueblo de los Reyes;Barrio del Niño Jesús;Rosedal;Pedregal de Coyoacán;El Rosedal;Pacifico', 'Coyoacán', 'Distrito Federal'),
(342,4336, 'Zapata', 'Coyoacán', 'Distrito Federal'),
(343,4337, 'Montserrat', 'Coyoacán', 'Distrito Federal'),
(344,4338, 'Mariana', 'Coyoacán', 'Distrito Federal'),
(345,4340, 'Insurgentes San Angel;Copilco Universidad ISSSTE;Copilco El Bajo', 'Coyoacán', 'Distrito Federal'),
(346,4350, 'Copilco;Altillo Universidad;Villas Copilco;Integración Latinoamericana;Acasulco', 'Coyoacán', 'Distrito Federal'),
(347,4359, 'Empleados Federales', 'Coyoacán', 'Distrito Federal'),
(348,4360, 'Copilco El Alto;Copilco Universidad', 'Coyoacán', 'Distrito Federal'),
(349,4368, 'Residencial la Cantera', 'Coyoacán', 'Distrito Federal'),
(350,4369, 'Pedregal de Santo Domingo', 'Coyoacán', 'Distrito Federal'),
(351,4370, 'Ciudad Jardín;Xotepingo 101;Atlántida', 'Coyoacán', 'Distrito Federal'),
(352,4380, 'Pueblo La Candelaria;El Rosario', 'Coyoacán', 'Distrito Federal'),
(354,4390, 'Huayamilpas;Nueva Diaz Ordaz', 'Coyoacán', 'Distrito Federal'),
(355,4400, 'Educación', 'Coyoacán', 'Distrito Federal'),
(356,4410, 'Petrolera Taxqueña;Tlalpan FOVISSSTE', 'Coyoacán', 'Distrito Federal'),
(357,4420, 'Ex-Ejido de San Francisco Culhuacán', 'Coyoacán', 'Distrito Federal'),
(358,4440, 'Culhuacán CTM Sección V;Culhuacán CTM Sección II;Culhuacán CTM Sección I', 'Coyoacán', 'Distrito Federal'),
(359,4450, 'El Centinela', 'Coyoacán', 'Distrito Federal'),
(360,4460, 'Avante', 'Coyoacán', 'Distrito Federal'),
(361,4470, 'Presidentes Ejidales 2a Sección;Presidentes Ejidales 1a Sección', 'Coyoacán', 'Distrito Federal'),
(362,4480, 'Culhuacán CTM CROC;Culhuacán CTM Sección VI;Culhuacán CTM Sección X-A;Culhuacán CTM Sección III', 'Coyoacán', 'Distrito Federal'),
(363,4489, 'Culhuacán CTM Sección VII', 'Coyoacán', 'Distrito Federal'),
(364,4490, 'Culhuacán CTM Canal Nacional;Culhuacán CTM Sección Piloto', 'Coyoacán', 'Distrito Federal'),
(365,4500, 'Jardines del Pedregal de San Ángel', 'Coyoacán', 'Distrito Federal'),
(366,4510, 'Universidad Nacional Autónoma de México', 'Coyoacán', 'Distrito Federal'),
(367,4513, 'Universidad Nacional Autónoma de México;Multifamiliar Para Maestros', 'Coyoacán', 'Distrito Federal'),
(368,4519, 'La Otra Banda', 'Coyoacán', 'Distrito Federal'),
(369,4530, 'Insurgentes Cuicuilco', 'Coyoacán', 'Distrito Federal'),
(370,4535, 'Torres del Maurel', 'Coyoacán', 'Distrito Federal'),
(371,4600, 'Pedregal de Santa Ursula', 'Coyoacán', 'Distrito Federal'),
(372,4610, 'Xotepingo', 'Coyoacán', 'Distrito Federal'),
(374,4620, 'Pueblo de San Pablo Tepetlapa', 'Coyoacán', 'Distrito Federal'),
(375,4630, 'Adolfo Ruiz Cortines', 'Coyoacán', 'Distrito Federal'),
(376,4640, 'El Reloj', 'Coyoacán', 'Distrito Federal'),
(377,4650, 'Los Fresnos;Pueblo de Santa Ursula Coapa', 'Coyoacán', 'Distrito Federal'),
(378,4660, 'Pedregal de La Zorra;Joyas del Pedregal', 'Coyoacán', 'Distrito Federal'),
(379,4700, 'Villa Panamericana;Pedregal de Carrasco', 'Coyoacán', 'Distrito Federal'),
(380,4710, 'Olímpica', 'Coyoacán', 'Distrito Federal'),
(381,4718, 'Vistas del Maurel', 'Coyoacán', 'Distrito Federal'),
(382,4719, 'Pedregal del Sur;Villas del Pedregal', 'Coyoacán', 'Distrito Federal'),
(383,4720, 'Pedregal del Maurel', 'Coyoacán', 'Distrito Federal'),
(384,4729, 'Rinconada las Playas INFONAVIT', 'Coyoacán', 'Distrito Federal'),
(385,4730, 'Bosques de Tetlameya;Cantil del Pedregal', 'Coyoacán', 'Distrito Federal'),
(386,4738, 'Villas del Imán;Modulo Social Imán', 'Coyoacán', 'Distrito Federal'),
(387,4739, 'El Caracol', 'Coyoacán', 'Distrito Federal'),
(288,4800, 'Alianza Popular Revolucionaria;Los Cedros', 'Coyoacán', 'Distrito Federal'),
(389,4810, 'Prados de Coyoacán', 'Coyoacán', 'Distrito Federal'),
(390,4815, 'Emiliano Zapata', 'Coyoacán', 'Distrito Federal'),
(391,4830, 'Los Cipreses;Los Ciruelos', 'Coyoacán', 'Distrito Federal'),
(392,4840, 'Ex-Ejido de San Pablo Tepetlapa', 'Coyoacán', 'Distrito Federal'),
(394,4843, 'Secretaria de Marina Armada de México', 'Coyoacán', 'Distrito Federal'),
(395,4849, 'Sector Marina', 'Coyoacán', 'Distrito Federal'),
(396,4850, 'Fuentes de Coyoacán', 'Coyoacán', 'Distrito Federal'),
(397,4859, 'El Hueso INFONAVIT', 'Coyoacán', 'Distrito Federal'),
(398,4870, 'Espartaco;Los Robles', 'Coyoacán', 'Distrito Federal'),
(399,4890, 'Los Olivos;Los Olivos;Jardines de Coyoacán', 'Coyoacán', 'Distrito Federal'),
(400,4899, 'El Parque de Coyoacán', 'Coyoacán', 'Distrito Federal');